In [115]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [116]:
df = pd.read_csv('IMDB Dataset.csv')
# df = df1.sample(20000)

In [117]:
# 1. Sample 10000 rows
# 2. Remove html tags
# 3. Remove special characters
# 4. Converting every thing to lower case
# 5. Removing Stop words
# 6. Stemming

In [118]:
df['sentiment'] = df['sentiment'].replace({'positive':1,'negative':0})

In [119]:
df['sentiment'] = df['sentiment'].astype(int)

In [120]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  str  
 1   sentiment  50000 non-null  int64
dtypes: int64(1), str(1)
memory usage: 63.2 MB


In [121]:
import re

def remove_html(text):
    return re.sub(r'<.*?>', '', text)


In [122]:
df['review'] = df['review'].apply(remove_html)

In [123]:
def convert_to_lowerCase(text):
    return text.lower()

In [124]:
df['review'] = df['review'].apply(convert_to_lowerCase)

In [125]:
df.head()

,review,sentiment
0,one of the other reviewers has mentioned that ...,1
1,a wonderful little production. the filming tec...,1
2,i thought this was a wonderful way to spend ti...,1
3,basically there's a family where a little boy ...,0
4,"petter mattei's ""love in the time of money"" is...",1


In [126]:
def remove_special_charcter(text):
    x = ''
    for i in text:
        if i.isalnum():
            x = x+i
        else:
            x = x+' '

    return x

In [127]:
df['review'] = df['review'].apply(remove_special_charcter)

In [128]:
df['review'] = df['review'].str.split().str.join(' ')

In [129]:
import nltk
# nltk.download('stopwords')f

In [130]:
from nltk.corpus import stopwords

In [161]:
stop_words = set(stopwords.words('english'))
# stop_words

In [132]:
def remove_stopwords(text):
    x = []
    for i in text.split():
        if i not in stop_words:
            x.append(i)
    y = x[:]
    x.clear()
    return y

In [133]:
df['review'] = df['review'].apply(remove_stopwords)

In [134]:
df.head()

,review,sentiment
0,"[one, reviewers, mentioned, watching, 1, oz, e...",1
1,"[wonderful, little, production, filming, techn...",1
2,"[thought, wonderful, way, spend, time, hot, su...",1
3,"[basically, family, little, boy, jake, thinks,...",0
4,"[petter, mattei, love, time, money, visually, ...",1


In [135]:
# performe stemming 
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [136]:
def perfom_stemming(text):
    y = []
    for i in text:
        y.append(ps.stem(i))

    z = y[:]
    y.clear()
    return z

In [137]:
df['review'] = df['review'].apply(perfom_stemming)

In [138]:
def perfom_join(list_input):
    return " ".join(list_input)

In [139]:
df['review'] = df['review'].apply(perfom_join)

In [ ]:
# ehle overall dataset ke saare unique words ko columns banata hai, phir har review me check karta hai ki har column wala word kitni
#  baar aaya hai aur uski frequency fill karta hai.
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

# this is BOW ()The Bag of Words (BoW) technique converts raw text into numerical feature vectors by counting word frequencies, which serves as the standard input for text-based Naive Bayes

In [141]:
X = cv.fit_transform(df['review'])

In [142]:
X.shape

(50000, 73392)

In [143]:
y = df['sentiment'].values
y

array([1, 1, 1, ..., 0, 0, 0], shape=(50000,))

In [154]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [145]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [146]:
model1 = GaussianNB()
model2 = MultinomialNB()
model3 = BernoulliNB()

In [ ]:

model2.fit(X_train,y_train)
model3.fit(X_train,y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"binarize binarize: float or None, default=0.0Threshold for binarizing (mapping to booleans) of sample features.If None, input is presumed to already consist of binary vectors.",0.0
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)Number of samples encountered for each class during fitting. Thisvalue is weighted by the sample weight when provided.","ndarray[float64](2,)","[20039.,19961.]"
"class_log_prior_ class_log_prior_: ndarray of shape (n_classes,)Log probability of each class (smoothed).","ndarray[float64](2,)","[-0.69,-0.7 ]"
"classes_ classes_: ndarray of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"feature_count_ feature_count_: ndarray of shape (n_classes, n_features)Number of samples encountered for each (class, feature)during fitting. This value is weighted by the sample weight whenprovided.","ndarray[float64](2, 73392)","[[ 81.,215., 1.,..., 1., 1., 1.], [ 71.,172., 0.,..., 0., 0., 0.]]"
"feature_log_prob_ feature_log_prob_: ndarray of shape (n_classes, n_features)Empirical log probability of features given a class, P(x_i|y).","ndarray[float64](2, 73392)","[[-5.5 ,-4.53,-9.21,...,-9.21,-9.21,-9.21], [-5.62,-4.75,-9.9 ,...,-9.9 ,-9.9 ,-9.9 ]]"


In [149]:
# # model1.fit(X_train,y_train)
# GaussianNB ko dense data chahiye, jabki tumhara X_train sparse matrix hai.

# Tumne sahi kiya tha .toarray() hata ke, because 50,000 × 73,392 ka dense matrix ~22 GB RAM le raha tha.
# Lekin mat karna 😅

# Kyuki X_train.toarray() tumhare case me ~22 GB memory maang raha hai. Tumhe wahi MemoryError dobara mil sakta hai.
# Conceptually bhi ye zyada appropriate hai: CountVectorizer se bana text-frequency data sparse hota hai, aur MultinomialNB specifically word-count/frequency features ke liye commonly used hai.

In [151]:
y_pred_model2 = model2.predict(X_test)
y_pred_model3 = model3.predict(X_test)

In [155]:
print("Accuarcy of MultinomialNB model : ",accuracy_score(y_test,y_pred_model2))
print("Accuarcy of BernoulliNB model : ",accuracy_score(y_test,y_pred_model3))

Accuarcy of MultinomialNB model :  0.8534
Accuarcy of BernoulliNB model :  0.8476


In [159]:
print(confusion_matrix(y_test, y_pred_model2))
print(classification_report(y_test, y_pred_model2))
print("-"*60)
print(confusion_matrix(y_test, y_pred_model3))
print(classification_report(y_test, y_pred_model3))

[[4320  641]
 [ 825 4214]]
              precision    recall  f1-score   support

           0       0.84      0.87      0.85      4961
           1       0.87      0.84      0.85      5039

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000

------------------------------------------------------------
[[4345  616]
 [ 908 4131]]
              precision    recall  f1-score   support

           0       0.83      0.88      0.85      4961
           1       0.87      0.82      0.84      5039

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000



    Making Function of whole process so we can predict sentiment just by reading review

In [162]:
def predict_review(review):

    review = remove_html(review)

    review = convert_to_lowerCase(review)

    review = remove_special_charcter(review)

    review = remove_stopwords(review)

    review = perfom_stemming(review)

    review = perfom_join(review)

    review = cv.transform([review])

    prediction = model2.predict(review)

    if prediction[0] == 1:
        return "Positive"
    else:
        return "Negative"

    testing with random review

In [172]:
predict_review("""
Salman Khan plays Pawan, a devotee of Lord Hanuman. He finds a lost little girl (Harshaali Malhotra) who is mute. It is eventually revealed that she is Pakistani, and Pawan must risk his life and freedom to travel there and return her to her home.

Khan plays his gentle character perfectly, but Malhotra--even silent-- steals the show. Both actors relate well to each other, and their camaraderie feels genuine. The plot is touching, serious, and heartwarming. Overall, it's a fantastic movie.
""")

'Positive'

In [171]:
predict_review("""
One of the worst movie of recent times, with very rubbish historic info. Scriptwriter, director and production should be ashamed to so laughable scripts. How come they make this comedy and give all wrong information to public.

You should not pay for this garbage and also should not waste your valuable time.

This film was not only pathetically terrible, but also a story line that made no sense. The usual sarcastic one liners fell flat.

I have to give this at least 1 star only cause I'm not allowed to give it less.
""")

'Negative'