#### Creating Array

In [2]:
import numpy as np

# one D or vector
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# matix or 2-D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3-d tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
#dtype

a = np.array([1,2,3],dtype=float)
print(a)
b = np.array([1,0,3],dtype=bool)
print(b)
c = np.array([1,2,3],dtype=complex)
print(c)



[1. 2. 3.]
[ True False  True]
[1.+0.j 2.+0.j 3.+0.j]


In [5]:
# arange act as range in numpy
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
# reshape 
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
# intializing a numpy using sort-cut

a = np.ones((2,5))
print(a)

b = np.zeros((2,4))
print(b)

c = np.random.random((3,3))
print(c)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.62014615 0.10053398 0.10602416]
 [0.6264346  0.81200137 0.58081635]
 [0.8132233  0.08540929 0.48091319]]


In [8]:
# linspace (linear spaces : ye na given range me provided no. of point ko iss range me equal distance pe generate krke array deta hai)
# Syntax: np.linspace(starting point,end point,number of elements or points)

a = np.linspace(-10,10,15)
print(a)


[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]


In [9]:
# identity : create identity matrix

a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Array Attribute

In [16]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [17]:
# ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [18]:
# shap
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [19]:
# size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [20]:
# itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [25]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


#### Changing Datatype

In [31]:
# astype()
print(a3.dtype)
a3.astype(np.int32)


int64


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#### Array Opertaion

In [33]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)

In [35]:
# Scaler operations
# arithmetic
print(a)
print(a*2)
print(a/2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [36]:
# relational
print(a>5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [41]:
# vector operation
print(a+b)
print(a*b)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


#### Array Functions

In [65]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
# sum/product/max/min
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))


93.0
8.0
443.0
164246080078080.0


In [59]:
# max / min in row and col wise 
# NOTE : axis = 0 cols and axis = 1 rows

print(np.max(a1,axis=1))
print(np.max(a1,axis=0))

print(np.sum(a1,axis=1))

[93. 65. 77.]
[77. 68. 93.]
[186. 104. 153.]


In [68]:
# mean/median/std/var
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))

4.0
4.0
2.581988897471611
6.666666666666667


In [71]:
# trignomentry functio
print(np.sin(a))

[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825]]


In [78]:
# dot product 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [79]:
print(np.dot(a2,a3))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [82]:
# log and exponent
print(np.exp(a2))

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


In [5]:
# round/floar/ceil
b = np.random.random((3,3))*100
print(b)
print(np.round(b))
print(np.floor(b))
print(np.ceil(b))

[[88.3089914  33.08747058 28.20964989]
 [30.76308101 38.60938282 12.54449358]
 [ 1.76846205 67.41375833  6.09205613]]
[[88. 33. 28.]
 [31. 39. 13.]
 [ 2. 67.  6.]]
[[88. 33. 28.]
 [30. 38. 12.]
 [ 1. 67.  6.]]
[[89. 34. 29.]
 [31. 39. 13.]
 [ 2. 68.  7.]]


#### Indexing and Slicing

In [10]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
print(a1)
a1[-1]

[0 1 2 3 4 5 6 7 8 9]


np.int64(9)

In [28]:
a1[1:7]

array([1, 2, 3, 4, 5, 6])

In [23]:
print(a2)
# print(a2[1:,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [26]:
a2[1,2]

np.int64(6)

In [18]:
a4 = np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
a4[2,1,1]

np.int64(22)

In [20]:
a4[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [22]:
a4[1,::2,::2]

array([[ 9, 11],
       [15, 17]])

#### Iterating

In [29]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [30]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [34]:
print(a4)
for i in a4:
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
#  editer convert n-D array to 1-D array 
for i in np.nditer(a4):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [33]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [41]:
print(np.max(a2))

11


#### Reshaping 

In [16]:
# reshape
a5 = np.arange(12).reshape((3,4))
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
# transpose
print(a5)
print(np.transpose(a5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [20]:
# ravel
np.ravel(a5)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Stacking 

In [ ]:
a1 = np.arange(12).reshape((3,4))
a2 = np.arange(12,24).reshape((3,4))

np.hstack((a1,a2))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
a3 = np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hsplit(a3,2)


[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [42]:
a = np.arange(12).reshape((4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
np.vsplit(a,2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]